### ISSUE TITLE
Huion New 1060+ working 99% with 2 minor issues

### ISSUE THREAD

**Issue by aceman500** [DIGImend/digimend-kernel-drivers#238] opened 2018-12-10 17:42 UTC
Thank you for your commitment to the digimend drivers!

My huion new 1060+ is working well with 2 minor issues:
1 If the tablet is plugged in on bootup it does not function.
lsmod shows hid_uclogic  has loaded but tablet does not work. Removing that module and plugging the tablet back in fixes it. Also if its not plugged in at boot then you plug it in it works.

2 It appears the table goes to sleep after inactivity. (you need to touch the table to wake it)
After that its seems to forget the monitor mapping and need to re run xsetwacom MapToOutput every time.

System:
Linux Fedora 28
Kernel ver: 4.18.16
using Xorg driver

**Comment by spbnick** [comment] 2020-04-26 15:25
Was able to reproduce this on a Fedora 29 VM, investigating.

**Comment by spbnick** [comment] 2020-04-26 16:08
This seems to be a problem with the way Fedora loads kernel modules at boot. When booting, it loads the stock kernel hid-uclogic module, even though the depmod configuration says it should load the one from the "extras" directory instead, the one installed by digimend-kernel-drivers. After it booted, you can unload the stock module with `modprobe -r hid-uclogic` and load the new module with `modprobe hid-uclogic`. This needs to be raised with Fedora developers.

**Comment by spbnick** [comment] 2020-04-26 16:16
I asked Red Hat kernel developers. Let's see if I get any answer.

**Comment by spbnick** [comment] 2020-05-17 15:29
A fix for the first issue is up in #394.

**Comment by spbnick** [comment] 2020-05-17 15:33
One approach to solve the second issue: https://askubuntu.com/questions/508236/how-can-i-run-code-whenever-a-usb-device-is-unplugged-without-requiring-root/516336#516336

**Comment by spbnick** [comment] 2020-05-18 08:43
#394 is merged.

**Closed** 2020-05-18 08:42 UTC
